name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'You made your issue. Will try to resolve your issue soon.'
        pr-message: 'You are successfully made Your PR. Will respond to that soon.'
